# Generated by Django 4.0.6 on 2022-07-08 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('max_student', models.PositiveIntegerField()),
                ('type_of_education', models.CharField(choices=[('OFFLINE', 'offline'), ('ONLINE', 'online'), ('-', '-')], default='-', max_length=20)),
                ('id_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools_app.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
