# Generated by Django 4.0.6 on 2022-07-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0002_rename_phone_number_1_communism_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communism',
            name='email',
        ),
    ]
