# Generated by Django 4.0.6 on 2022-07-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_alter_student_gender_delete_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'second_name', 'date_of_birth', 'email')},
        ),
    ]
